name: flutter_todo_drift
description: A Flutter todo application built with Drift database for local storage and Riverpod for state management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  drift_flutter: ^0.2.4
  drift: ^2.26.0
  get_it: ^8.0.3
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.26.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
